plugins {
    id 'application'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'aravii.AravII'
}

checkstyle {
    toolVersion = '11.0.0'
}

tasks.withType(Checkstyle).configureEach {
    configDirectory = file('config/checkstyle')
}

tasks.named('jar') {
    manifest {
        attributes('Main-Class': application.mainClass.get())
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}
